//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorModel", Namespace="http://schemas.datacontract.org/2004/07/VSQuickShareService.Model")]
    [System.SerializableAttribute()]
    public partial class ErrorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/VSQuickShareService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VSQuickShareServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetShareKey", ReplyAction="http://tempuri.org/IService/GetShareKeyResponse")]
        bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyResponse GetShareKey(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetShareKey", ReplyAction="http://tempuri.org/IService/GetShareKeyResponse")]
        System.Threading.Tasks.Task<bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyResponse> GetShareKeyAsync(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSharedCode", ReplyAction="http://tempuri.org/IService/AddSharedCodeResponse")]
        bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeResponse AddSharedCode(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddSharedCode", ReplyAction="http://tempuri.org/IService/AddSharedCodeResponse")]
        System.Threading.Tasks.Task<bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeResponse> AddSharedCodeAsync(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.CompositeType GetDataUsingDataContract(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.CompositeType> GetDataUsingDataContractAsync(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.CompositeType composite);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShareKey", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetShareKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sharedKey;
        
        public GetShareKeyRequest() {
        }
        
        public GetShareKeyRequest(string sharedKey) {
            this.sharedKey = sharedKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShareKeyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetShareKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetShareKeyResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.ErrorModel errorModel;
        
        public GetShareKeyResponse() {
        }
        
        public GetShareKeyResponse(string GetShareKeyResult, bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.ErrorModel errorModel) {
            this.GetShareKeyResult = GetShareKeyResult;
            this.errorModel = errorModel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSharedCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddSharedCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string uniqueCode;
        
        public AddSharedCodeRequest() {
        }
        
        public AddSharedCodeRequest(string userId, string code, string uniqueCode) {
            this.userId = userId;
            this.code = code;
            this.uniqueCode = uniqueCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSharedCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddSharedCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddSharedCodeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.ErrorModel errorModel;
        
        public AddSharedCodeResponse() {
        }
        
        public AddSharedCodeResponse(string AddSharedCodeResult, bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.ErrorModel errorModel) {
            this.AddSharedCodeResult = AddSharedCodeResult;
            this.errorModel = errorModel;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.IService>, bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyResponse bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.IService.GetShareKey(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyRequest request) {
            return base.Channel.GetShareKey(request);
        }
        
        public string GetShareKey(string sharedKey, out bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.ErrorModel errorModel) {
            bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyRequest inValue = new bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyRequest();
            inValue.sharedKey = sharedKey;
            bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyResponse retVal = ((bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.IService)(this)).GetShareKey(inValue);
            errorModel = retVal.errorModel;
            return retVal.GetShareKeyResult;
        }
        
        public System.Threading.Tasks.Task<bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyResponse> GetShareKeyAsync(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.GetShareKeyRequest request) {
            return base.Channel.GetShareKeyAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeResponse bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.IService.AddSharedCode(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeRequest request) {
            return base.Channel.AddSharedCode(request);
        }
        
        public string AddSharedCode(string userId, string code, string uniqueCode, out bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.ErrorModel errorModel) {
            bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeRequest inValue = new bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeRequest();
            inValue.userId = userId;
            inValue.code = code;
            inValue.uniqueCode = uniqueCode;
            bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeResponse retVal = ((bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.IService)(this)).AddSharedCode(inValue);
            errorModel = retVal.errorModel;
            return retVal.AddSharedCodeResult;
        }
        
        public System.Threading.Tasks.Task<bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeResponse> AddSharedCodeAsync(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.AddSharedCodeRequest request) {
            return base.Channel.AddSharedCodeAsync(request);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.CompositeType GetDataUsingDataContract(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.CompositeType> GetDataUsingDataContractAsync(bhojarajsahu88.VSQuickShare.VSQuickShareServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
